### ISSUE TITLE
Running code causes error

### ISSUE THREAD

**Issue by EdmundHernandezStudent** [IkeHasAPlan/Stock-Data-Visualizer#1]
Enter the start date (YYYY-MM-DD): 2003
Enter the end date (YYYY-MM-DD): 2006
Invalid date format. Please use YYYY-MM-DD.
Enter the start date (YYYY-MM-DD): 2003-12-01
Enter the end date (YYYY-MM-DD): 2005-02-05
Select the Time Series of the chart you want to Generate
1. Intraday
2. Daily
3. Weekly
4. Monthly
Enter the time series option (1, 2, 3, 4): 2
Error: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\edmun\Downloads\Stock-Data-Visualizer-main\Stock-Data-Visualizer-main\stock_data_vizualizer.py", line 101, in <module>
    main()
  File "C:\Users\edmun\Downloads\Stock-Data-Visualizer-main\Stock-Data-Visualizer-main\stock_data_vizualizer.py", line 20, in main
    data = retrieve_data(time_series, symbols, key)
  File "C:\Users\edmun\Downloads\Stock-Data-Visualizer-main\Stock-Data-Visualizer-main\stock_data_vizualizer.py", line 52, in retrieve_data
    response = requests.get(url)
  File "C:\Users\edmun\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\edmun\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\edmun\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\edmun\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Users\edmun\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'fhttps://www.alphavantage.co/query?function={function}&symbol={symbol}&apikey={api_key}'

**Comment by EdmundHernandezStudent** [comment]
I will close this now, so now its runs (time for bug fixing)
